version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
    ports:
      - 5432:5432
  webapp:
    build: .
    ports:
      - 3000:3000
    env_file: .env.local
    volumes:
      - .:/app/
